#!/bin/bash
#
#   deploy.sh
#   - execute this file from the root filesystem of the repository
#     i.e. mkDeploy
#
# This file runs a few 'mike' checks to ensure that the correct version is deployed to the
# GitHub pages , with ending up with a 404 error
set -e
mkdocs gh-deploy